// "use client";
import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import Footer from "../custom-components/Footer";

import Navbar from "@/custom-components/Navbar";
import { ThemeProvider } from "next-themes";
import Provider from "../contexts";
import "./globals.css";

const WalletProvider = dynamic(() => import("@/providers/WalletProvider"), {
  // ssr: false,
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autonomint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  cookies,
}: {
  children: React.ReactNode;
  cookies: string | null;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={`h-screen w-screen flex justify-center items-center`}>
        <div className="bg-white rounded-lg shadow-lg w-full h-full md:w-[100%] md:max-w-full md:h-[100vh] md:max-h-[100vh] flex flex-col dark:bg-black">
          <QueryProvider>
            <WalletProvider cookies={cookies}>
              <Provider>
                <ThemeProvider attribute="class">
                  <Navbar />
                  {/* <AppNavbar /> */}
                  <div
                    id={"body-scroll-container"}
                    className="flex-grow overflow-y-auto no-scrollbar border-r-0"
                  >
                    {children}
                    <Footer />
                  </div>
                </ThemeProvider>
              </Provider>
            </WalletProvider>
          </QueryProvider>
        </div>
      </body>
      <Toaster
        richColors
        position="top-right"
        className="dark:bg-custom-gradient-to-top"
      />
    </html>
  );
}
