import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";

const ToasterContainerWrapper = dynamic(
  () => import("@/design-systems/molecule/toaster-container-wrapper")
);

import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import WalletProvider from "@/providers/WalletProvider";
import Provider from "@/contexts";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/design-systems/organisms/navbar/Navbar";
import Footer from "@/design-systems/organisms/Footer";
import InviteCodePopup from "@/design-systems/molecule/popups/InviteCodePopup";
import SwitchChainPopup from "@/design-systems/molecule/popups/WalletConnect";
import BetaConfirmation from "@/design-systems/molecule/popups/BetaConfirmation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autonomint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={`h-screen w-screen flex justify-center items-center`}>
        <div className="bg-white rounded-lg shadow-lg w-full h-full md:w-[100%] md:max-w-full md:h-[100vh] md:max-h-[100vh] flex flex-col dark:bg-black">
          <QueryProvider>
            <WalletProvider cookies={""}>
              <Provider>
                <ThemeProvider attribute="class">
                  <Navbar />
                  <div
                    id={"body-scroll-container"}
                    className="flex-grow overflow-y-auto no-scrollbar border-r-0"
                  >
                    {children}
                    <Footer />
                    {/* <InviteCodePopup /> */}
                    <SwitchChainPopup />
                    <BetaConfirmation />
                  </div>
                </ThemeProvider>
              </Provider>
            </WalletProvider>
          </QueryProvider>
        </div>
        <ToasterContainerWrapper />
      </body>
    </html>
  );
}
