export const borrowingContractAbi = [
    {
      type: 'error',
      inputs: [{ name: 'target', internalType: 'address', type: 'address' }],
      name: 'AddressEmptyCode',
    },
    { type: 'error', inputs: [], name: 'Borrowing_DepositFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_GettingETHPriceFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_LiquidateBurnFailed' },
    {
      type: 'error',
      inputs: [],
      name: 'Borrowing_LiquidateEthTransferToCdsFailed',
    },
    { type: 'error', inputs: [], name: 'Borrowing_WithdrawBurnFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_WithdrawEthTransferFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_WithdrawUSDaTransferFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_abondMintFailed' },
    { type: 'error', inputs: [], name: 'Borrowing_usdaMintFailed' },
    {
      type: 'error',
      inputs: [
        { name: 'implementation', internalType: 'address', type: 'address' },
      ],
      name: 'ERC1967InvalidImplementation',
    },
    { type: 'error', inputs: [], name: 'ERC1967NonPayable' },
    { type: 'error', inputs: [], name: 'FailedInnerCall' },
    { type: 'error', inputs: [], name: 'InvalidInitialization' },
    {
      type: 'error',
      inputs: [{ name: 'optionType', internalType: 'uint16', type: 'uint16' }],
      name: 'InvalidOptionType',
    },
    { type: 'error', inputs: [], name: 'NotInitializing' },
    {
      type: 'error',
      inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
      name: 'OwnableInvalidOwner',
    },
    {
      type: 'error',
      inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
      name: 'OwnableUnauthorizedAccount',
    },
    { type: 'error', inputs: [], name: 'ReentrancyGuardReentrantCall' },
    {
      type: 'error',
      inputs: [
        { name: 'bits', internalType: 'uint8', type: 'uint8' },
        { name: 'value', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'SafeCastOverflowedUintDowncast',
    },
    { type: 'error', inputs: [], name: 'UUPSUnauthorizedCallContext' },
    {
      type: 'error',
      inputs: [{ name: 'slot', internalType: 'bytes32', type: 'bytes32' }],
      name: 'UUPSUnsupportedProxiableUUID',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'user',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        { name: 'index', internalType: 'uint64', type: 'uint64', indexed: false },
        {
          name: 'depositedAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'normalizedAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'depositedTime',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'ethPrice',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'borrowAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'strikePrice',
          internalType: 'uint64',
          type: 'uint64',
          indexed: false,
        },
        {
          name: 'optionsFees',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'strikePricePercent',
          internalType: 'enum IOptions.StrikePrice',
          type: 'uint8',
          indexed: false,
        },
        { name: 'APR', internalType: 'uint8', type: 'uint8', indexed: false },
      ],
      name: 'Deposit',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'version',
          internalType: 'uint64',
          type: 'uint64',
          indexed: false,
        },
      ],
      name: 'Initialized',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'index', internalType: 'uint64', type: 'uint64', indexed: false },
        {
          name: 'liquidationAmount',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'profits',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'ethAmount',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'availableLiquidationAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Liquidate',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'previousOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'newOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'OwnershipTransferred',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'implementation',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'Upgraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'user',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        { name: 'index', internalType: 'uint64', type: 'uint64', indexed: false },
        {
          name: 'withdrawTime',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'withdrawAmount',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'noOfAbond',
          internalType: 'uint128',
          type: 'uint128',
          indexed: false,
        },
        {
          name: 'borrowDebt',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Withdraw',
    },
    {
      type: 'function',
      inputs: [],
      name: 'UPGRADE_INTERFACE_VERSION',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'admin',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'calculateCumulativeRate',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_amount', internalType: 'uint256', type: 'uint256' },
        { name: 'currentEthPrice', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'calculateRatio',
      outputs: [{ name: '', internalType: 'uint64', type: 'uint64' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        {
          name: '_strikePercent',
          internalType: 'enum IOptions.StrikePrice',
          type: 'uint8',
        },
        { name: '_strikePrice', internalType: 'uint64', type: 'uint64' },
        { name: '_volatility', internalType: 'uint256', type: 'uint256' },
        { name: '_depositingAmount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'depositTokens',
      outputs: [],
      stateMutability: 'payable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'user', internalType: 'address', type: 'address' },
        { name: 'aBondAmount', internalType: 'uint128', type: 'uint128' },
      ],
      name: 'getAbondYields',
      outputs: [
        { name: '', internalType: 'uint128', type: 'uint128' },
        { name: '', internalType: 'uint256', type: 'uint256' },
        { name: '', internalType: 'uint256', type: 'uint256' },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'getLTV',
      outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'getUSDValue',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_tokenAddress', internalType: 'address', type: 'address' },
        { name: '_cds', internalType: 'address', type: 'address' },
        { name: '_abondToken', internalType: 'address', type: 'address' },
        { name: '_multiSign', internalType: 'address', type: 'address' },
        { name: '_priceFeedAddress', internalType: 'address', type: 'address' },
        { name: 'chainId', internalType: 'uint64', type: 'uint64' },
        { name: '_globalVariables', internalType: 'address', type: 'address' },
      ],
      name: 'initialize',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'lastCumulativeRate',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'user', internalType: 'address', type: 'address' },
        { name: 'index', internalType: 'uint64', type: 'uint64' },
      ],
      name: 'liquidate',
      outputs: [],
      stateMutability: 'payable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'owner',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'proxiableUUID',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'user', internalType: 'address', type: 'address' },
        { name: 'aBondAmount', internalType: 'uint128', type: 'uint128' },
      ],
      name: 'redeemYields',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'renounceOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_APR', internalType: 'uint8', type: 'uint8' },
        { name: '_ratePerSec', internalType: 'uint128', type: 'uint128' },
      ],
      name: 'setAPR',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_admin', internalType: 'address', type: 'address' }],
      name: 'setAdmin',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_bondRatio', internalType: 'uint64', type: 'uint64' }],
      name: 'setBondRatio',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_borrowLiquidation', internalType: 'address', type: 'address' },
      ],
      name: 'setBorrowLiquidation',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_LTV', internalType: 'uint8', type: 'uint8' }],
      name: 'setLTV',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_options', internalType: 'address', type: 'address' }],
      name: 'setOptions',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_treasury', internalType: 'address', type: 'address' }],
      name: 'setTreasury',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
      name: 'updateLastEthVaultValue',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: 'usdaPrice', internalType: 'uint32', type: 'uint32' }],
      name: 'updateRatePerSecByUSDaPrice',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'newImplementation', internalType: 'address', type: 'address' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'upgradeToAndCall',
      outputs: [],
      stateMutability: 'payable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'usda',
      outputs: [{ name: '', internalType: 'contract IUSDa', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_toAddress', internalType: 'address', type: 'address' },
        { name: '_index', internalType: 'uint64', type: 'uint64' },
      ],
      name: 'withDraw',
      outputs: [],
      stateMutability: 'payable',
    },
  ] as const