export const cdsAbi = [
  {
    type: "error",
    inputs: [{ name: "target", internalType: "address", type: "address" }],
    name: "AddressEmptyCode",
  },
  {
    type: "error",
    inputs: [
      { name: "implementation", internalType: "address", type: "address" },
    ],
    name: "ERC1967InvalidImplementation",
  },
  { type: "error", inputs: [], name: "ERC1967NonPayable" },
  { type: "error", inputs: [], name: "FailedInnerCall" },
  { type: "error", inputs: [], name: "InvalidInitialization" },
  {
    type: "error",
    inputs: [{ name: "optionType", internalType: "uint16", type: "uint16" }],
    name: "InvalidOptionType",
  },
  { type: "error", inputs: [], name: "NotInitializing" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "ReentrancyGuardReentrantCall" },
  {
    type: "error",
    inputs: [
      { name: "bits", internalType: "uint8", type: "uint8" },
      { name: "value", internalType: "uint256", type: "uint256" },
    ],
    name: "SafeCastOverflowedUintDowncast",
  },
  { type: "error", inputs: [], name: "UUPSUnauthorizedCallContext" },
  {
    type: "error",
    inputs: [{ name: "slot", internalType: "bytes32", type: "bytes32" }],
    name: "UUPSUnsupportedProxiableUUID",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "user",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      { name: "index", internalType: "uint64", type: "uint64", indexed: false },
      {
        name: "depositedUSDa",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "depositedUSDT",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "depositedTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "ethPriceAtDeposit",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "lockingPeriod",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "liquidationAmount",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "optedForLiquidation",
        internalType: "bool",
        type: "bool",
        indexed: false,
      },
    ],
    name: "Deposit",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "version",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
    ],
    name: "Initialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "implementation",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "Upgraded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "user",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      { name: "index", internalType: "uint64", type: "uint64", indexed: false },
      {
        name: "withdrawUSDa",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "withdrawTime",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "withdrawETH",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "ethPriceAtWithdraw",
        internalType: "uint128",
        type: "uint128",
        indexed: false,
      },
      {
        name: "optionsFees",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "optionsFeesWithdrawn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdraw",
  },
  {
    type: "function",
    inputs: [],
    name: "UPGRADE_INTERFACE_VERSION",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "admin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "fees", internalType: "uint128", type: "uint128" }],
    name: "calculateCumulativeRate",
    outputs: [{ name: "", internalType: "uint128", type: "uint128" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "cdsCount",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "cdsDetails",
    outputs: [
      { name: "index", internalType: "uint64", type: "uint64" },
      { name: "hasDeposited", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "usdtAmount", internalType: "uint128", type: "uint128" },
      { name: "usdaAmount", internalType: "uint128", type: "uint128" },
      { name: "_liquidate", internalType: "bool", type: "bool" },
      { name: "_liquidationAmount", internalType: "uint128", type: "uint128" },
      { name: "lockingPeriod", internalType: "uint128", type: "uint128" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "depositor", internalType: "address", type: "address" },
      { name: "index", internalType: "uint64", type: "uint64" },
    ],
    name: "getCDSDepositDetails",
    outputs: [
      {
        name: "",
        internalType: "struct CDSInterface.CdsAccountDetails",
        type: "tuple",
        components: [
          { name: "depositedTime", internalType: "uint64", type: "uint64" },
          { name: "depositedAmount", internalType: "uint256", type: "uint256" },
          { name: "withdrawedTime", internalType: "uint64", type: "uint64" },
          {
            name: "withdrawedAmount",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "withdrawed", internalType: "bool", type: "bool" },
          { name: "depositPrice", internalType: "uint128", type: "uint128" },
          { name: "depositValue", internalType: "uint128", type: "uint128" },
          { name: "depositValueSign", internalType: "bool", type: "bool" },
          { name: "optedLiquidation", internalType: "bool", type: "bool" },
          {
            name: "InitialLiquidationAmount",
            internalType: "uint128",
            type: "uint128",
          },
          {
            name: "liquidationAmount",
            internalType: "uint128",
            type: "uint128",
          },
          {
            name: "liquidationindex",
            internalType: "uint128",
            type: "uint128",
          },
          {
            name: "normalizedAmount",
            internalType: "uint256",
            type: "uint256",
          },
        ],
      },
      { name: "", internalType: "uint64", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_usda", internalType: "address", type: "address" },
      { name: "priceFeed", internalType: "address", type: "address" },
      { name: "_usdt", internalType: "address", type: "address" },
      { name: "_multiSign", internalType: "address", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_usdaAmount", internalType: "uint128", type: "uint128" },
      { name: "usdaPrice", internalType: "uint64", type: "uint64" },
      { name: "usdtPrice", internalType: "uint64", type: "uint64" },
    ],
    name: "redeemUSDT",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_admin", internalType: "address", type: "address" }],
    name: "setAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_address", internalType: "address", type: "address" }],
    name: "setBorrowLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_address", internalType: "address", type: "address" }],
    name: "setBorrowingContract",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_address", internalType: "address", type: "address" }],
    name: "setGlobalVariables",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_treasury", internalType: "address", type: "address" }],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "percent", internalType: "uint8", type: "uint8" }],
    name: "setUSDaLimit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "amount", internalType: "uint64", type: "uint64" }],
    name: "setUsdtLimit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_timeLimit", internalType: "uint64", type: "uint64" }],
    name: "setWithdrawTimeLimit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "totalAvailableLiquidationAmount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "totalCdsDepositedAmount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "index", internalType: "uint128", type: "uint128" },
      {
        name: "liquidationData",
        internalType: "struct CDSInterface.LiquidationInfo",
        type: "tuple",
        components: [
          {
            name: "liquidationAmount",
            internalType: "uint128",
            type: "uint128",
          },
          { name: "profits", internalType: "uint128", type: "uint128" },
          { name: "ethAmount", internalType: "uint128", type: "uint128" },
          {
            name: "availableLiquidationAmount",
            internalType: "uint256",
            type: "uint256",
          },
        ],
      },
    ],
    name: "updateLiquidationInfo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
    name: "updateTotalAvailableLiquidationAmount",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_amount", internalType: "uint128", type: "uint128" }],
    name: "updateTotalCdsDepositedAmount",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_amount", internalType: "uint128", type: "uint128" }],
    name: "updateTotalCdsDepositedAmountWithOptionFees",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "newImplementation", internalType: "address", type: "address" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "usda",
    outputs: [{ name: "", internalType: "contract IUSDa", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "usdaLimit",
    outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "usdtAmountDepositedTillNow",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "usdtLimit",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_index", internalType: "uint64", type: "uint64" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "payable",
  },
] as const;
