import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../customComponents/Navbar";
import Footer from "../customComponents/Footer";
import AppNavbar from "../customComponents/AppNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autonomint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={`h-screen w-screen bg-gray-50 flex justify-center items-center`}
      >
        <div className="bg-white border border-solid border-gray-200 rounded-lg shadow-lg w-full h-full md:w-[95%] md:max-w-full md:h-[95%] md:max-h-[95vh] flex flex-col">
          {/* <Navbar /> */}
          <AppNavbar />
          <div className="flex-grow overflow-y-auto">{children}</div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
